steps:

# Build the gcs-uploader binary and put it into the builder image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg=cmd=./cmd/gcs-uploader/', '-t', 'gcr.io/$PROJECT_ID/gcs-uploader', '.']

# Print the manifest.
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cat', 'gs://gcp-dev-buk-eu-lcm-test-1111/lifecycle.txt']

# Push the images.
images:
- 'gcr.io/$PROJECT_ID/gcs-uploader'
