steps:
- name: 'eu.gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg=cmd=./cmd/gcs-fetcher/', '-t', 'eu.gcr.io/$PROJECT_ID/gcs-fetcher', '.']
- name: 'eu.gcr.io/$PROJECT_ID/gcs-fetcher'
  args: ['--help']

# Build the gcs-uploader binary and put it into the builder image.
- name: 'eu.gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg=cmd=./cmd/gcs-uploader/', '-t', 'eu.gcr.io/$PROJECT_ID/gcs-uploader', '.']
- name: 'gcr.io/$PROJECT_ID/gcs-uploader'
  args: ['--help']

# Print the manifest.
- name: 'eu.gcr.io/cloud-builders/gsutil'
  args: ['cat', 'gs://gcp-dev-buk-eu-lcm-test-1111/lifecycle.txt']

# Push the images.
images:
- 'eu.gcr.io/$PROJECT_ID/gcs-fetcher'
- 'eu.gcr.io/$PROJECT_ID/gcs-uploader'
