steps:
- name: "eu.gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['gsutil lifecycle set lifecycle.txt gs://gcp-dev-buk-eu-lcm-test-1111']
images:
- 'eu.gcr.io/$PROJECT_ID/helloworld-image'
